name: Dependency Check

on:
  pull_request:
    branches:
      - main

jobs:
  check_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Check for Dependency Issues
        run: npm audit > issues/issues-file.txt || true

      - name: Comment on PR with Issues
        run: |
          echo "PR has dependency issues:" > pr_comment.txt
          issues_content="$(cat issues/issues-file.txt)"
          if ! echo "$issues_content" | grep -q "found 0 vulnerabilities"; then
            echo "$issues_content" >> pr_comment.txt
            COMMENT_BODY=$(cat pr_comment.txt)
          
            # Get the PR number
            PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          
            # Comment on the PR using GitHub REST API
            curl -X POST \
              -H "Authorization: Bearer $ACCESS_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments" \
              -d "{\"body\":\"$COMMENT_BODY\"}"
          else
            echo "No dependency issues found."
          fi
      
      - name: Check for Critical or High Vulnerabilities
        run: |
          if grep -qE "critical|high" issues/issues-file.txt; then
            echo "Critical or high dependency issues found. Rejecting PR."
            exit 1
          fi
